apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: example-allow-all-netpolicy
  annotations:
    demo.environment: "prod"
---
apiVersion: k8s.ovn.org/v1
kind: EgressFirewall
metadata:
  name: default
  annotations:
    demo.environment: "prod"
---
apiVersion: policy.networking.k8s.io/v1alpha1
kind: AdminNetworkPolicy
metadata:
  name: allow-all-adminpolicy
  annotations:
    demo.environment: "prod"